version: '3.8'

services:
  app:
    ## read php image from our custom docker image ##
    container_name: laravel_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./nginx/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./:/var/www
      - ./entrypoint.sh:/var/www/entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      #- redis
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ## expose the mysql port to our machine so we can access it from any mysql-client like TablePlus ##
    ports:
      - "3306:3306"
    ## keep mysql data on localhost so we don't lose them ##
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    networks:
      - laravel_network


  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
